clinica_dental/appointments/urls.py
from django.urls import path
from appointments import views


urlpatterns = [

    path(
        route = '',
        view = views.AppointmentsHomeView.as_view(),
        name = "home",
    ),

    path(
        route = 'appointments/work_blocks',
        view = views.WorkBlocksView.as_view(),
        name = "work_blocks",
    ),

    path(
        route = 'appointments/add_work_blocks',
        view = views.AddWorkBlocksView.as_view(),
        name = "add_work_blocks",
    ),

    path(
        route = 'appointments/delete_work_blocks/<int:pk>',
        view = views.DeleteWorkBlocksView.as_view(),
        name = "delete_work_blocks",
    ),

    path(
        route = 'appointments/feed',
        view = views.AppointmentsFeedView.as_view(),
        name = "feed",
    ),

    path(
        route = 'appointments/add_preview',
        view = views.AddAppointmentsPreview.as_view(),
        name = "add_preview",
    ),

    path(
        route = 'appointments/add_appointment/<int:block_id>',
        view = views.AddAppointmentsView.as_view(),
        name = "add_appointments",
    ),

    path(
        route = 'appointments/delete_appointment/<int:pk>',
        view = views.DeleteAppointmentsView.as_view(),
        name = "delete_appointments",
    ),

    path(
        route = 'appointments/feed_doctors',
        view = views.AppointmentsFeedDoctorView.as_view(),
        name = "feed_doctors",
    ),

    path(
        route = 'appointments/update_appointment/<int:pk>',
        view = views.UpdateAppointmentsView.as_view(),
        name = "update_appointments",
    ),

    path(
        route = 'consultations/add/<int:appointment_id>',
        view = views.AddConsultationsView.as_view(),
        name = "add_consultations",
    ),

]

clinica_dental/clinica_dental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('appointments.urls', 'appointments'), namespace='appointments')),

    path('users/', include(('users.urls', 'users'), namespace='users')),
    
    path('medical_records/', include(('medical_records.urls', 'medical_records'), namespace='medical_records')),

    path('consultations/', include(('consultations.urls', 'consultations'), namespace='consultations')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinica_dental/users/urls.py
from django.urls import path
from users import views


urlpatterns = [

    path(
        route = 'login/',
        view = views.LoginView.as_view(),
        name = "login",
    ),

    path(
        route = 'signup/',
        view = views.SignUpView.as_view(),
        name = "signup",
    ),

    path(
        route = 'logout/',
        view = views.LogOutView.as_view(),
        name = "logout",
    ),

    path(
        route = 'superuser/',
        view = views.SuperUserView.as_view(),
        name = "superuser",
    ),

    path(
        route = 'edit_user/<int:pk>',
        view = views.EditUserView.as_view(),
        name = "edit_user",
    ),

    path(
        route = 'statistics',
        view = views.StatisticsFeedView.as_view(),
        name = "statistics",
    ),

]

clinica_dental/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

clinica_dental/templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'appointments:home' %}">
            <img src="{% static 'img/clinica-icon.png' %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <a href="">
                        <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:superuser' %}">
                        <i class="fas fa-id-card-alt"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>