clinica_dental/appointments/urls.py
from django.urls import path
from appointments import views


urlpatterns = [

    path(
        route = '',
        view = views.AppointmentsHomeView.as_view(),
        name = "home",
    ),

    path(
        route = 'appointments/work_blocks',
        view = views.WorkBlocksView.as_view(),
        name = "work_blocks",
    ),

    path(
        route = 'appointments/add_work_blocks',
        view = views.AddWorkBlocksView.as_view(),
        name = "add_work_blocks",
    ),

    path(
        route = 'appointments/delete_work_blocks/<int:pk>',
        view = views.DeleteWorkBlocksView.as_view(),
        name = "delete_work_blocks",
    ),

    path(
        route = 'appointments/feed',
        view = views.AppointmentsFeedView.as_view(),
        name = "feed",
    ),

    path(
        route = 'appointments/add_preview',
        view = views.AddAppointmentsPreview.as_view(),
        name = "add_preview",
    ),

    path(
        route = 'appointments/add_appointment/<int:block_id>',
        view = views.AddAppointmentsView.as_view(),
        name = "add_appointments",
    ),

    path(
        route = 'appointments/delete_appointment/<int:pk>',
        view = views.DeleteAppointmentsView.as_view(),
        name = "delete_appointments",
    ),

    path(
        route = 'appointments/feed_doctors',
        view = views.AppointmentsFeedDoctorView.as_view(),
        name = "feed_doctors",
    ),

    path(
        route = 'appointments/update_appointment/<int:pk>',
        view = views.UpdateAppointmentsView.as_view(),
        name = "update_appointments",
    ),

    path(
        route = 'consultations/add/<int:appointment_id>',
        view = views.AddConsultationsView.as_view(),
        name = "add_consultations",
    ),

]

clinica_dental/clinica_dental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('appointments.urls', 'appointments'), namespace='appointments')),

    path('users/', include(('users.urls', 'users'), namespace='users')),
    
    path('medical_records/', include(('medical_records.urls', 'medical_records'), namespace='medical_records')),

    path('consultations/', include(('consultations.urls', 'consultations'), namespace='consultations')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinica_dental/medical_records/urls.py
from django.urls import path
from medical_records import views


urlpatterns = [

    path(
        route = 'medical_records/feed',
        view = views.MedicalRecordsFeedView.as_view(),
        name = 'feed',
    ),

    path(
        route = 'medical_records/create',
        view = views.CreateMedicalRecordView.as_view(),
        name = 'create',
    ),

    path(
        route = 'medical_records/feed_doctors',
        view = views.MedicalRecordsDoctorsFeedView.as_view(),
        name = 'feed_doctors',
    ),

    path(
        route = 'medical_records/consultations_feed/<int:user_id>',
        view = views.ConsultationsDoctorFeedView.as_view(),
        name = 'feed_consultations',
    ),

    path(
        route = 'medical_records/consultations_feed_pacient/<int:user_id>',
        view = views.ConsultationsPacientFeedView.as_view(),
        name = 'feed_pacient',
    ),

    path(
        route = 'medical_records/account',
        view = views.AccountFeedView.as_view(),
        name = 'account',
    ),

    path(
        route = 'medical_records/send_bill/<int:appointment_id>',
        view = views.SendBillView.as_view(),
        name = 'send_bill',
    ),

]

clinica_dental/users/urls.py
from django.urls import path
from users import views


urlpatterns = [

    path(
        route = 'login/',
        view = views.LoginView.as_view(),
        name = "login",
    ),

    path(
        route = 'signup/',
        view = views.SignUpView.as_view(),
        name = "signup",
    ),

    path(
        route = 'logout/',
        view = views.LogOutView.as_view(),
        name = "logout",
    ),

    path(
        route = 'superuser/',
        view = views.SuperUserView.as_view(),
        name = "superuser",
    ),

    path(
        route = 'edit_user/<int:pk>',
        view = views.EditUserView.as_view(),
        name = "edit_user",
    ),

    path(
        route = 'statistics',
        view = views.StatisticsFeedView.as_view(),
        name = "statistics",
    ),

]

clinica_dental/appointments/models.py
from django.db import models
from django.contrib.auth.models import User

from users.models import Profile


class WorkBlocks(models.Model):

    day = models.CharField(max_length=10)
    hour = models.CharField(max_length=10)
    doctor_name = models.CharField(max_length=255)

    doctor = models.ForeignKey(User, on_delete=models.CASCADE)


class Appointments(models.Model):

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=255)

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    block = models.ForeignKey(WorkBlocks, on_delete=models.CASCADE)


class Consultations(models.Model):

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    doctor = models.ForeignKey(User, on_delete=models.CASCADE)
    block = models.ForeignKey(WorkBlocks, on_delete=models.CASCADE)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    appointment = models.ForeignKey(Appointments, on_delete=models.CASCADE)

    price = models.IntegerField()
    medicaments = models.TextField()
    symtoms = models.TextField()
    treatment = models.TextField()
    payment = models.CharField(max_length=255)

clinica_dental/appointments/forms.py
from django import forms

from appointments.models import WorkBlocks, Appointments, Consultations

class WorkBlockForm(forms.ModelForm):

    class Meta():
        
        model = WorkBlocks
        fields = ('doctor', 'doctor_name', 'hour', 'day')


class AppointmentsForm(forms.ModelForm):

    class Meta():

        model = Appointments
        fields = ('status', 'user', 'block')


class EditAppointmentsForm(forms.ModelForm):

    class Meta():

        model = Appointments
        fields = ('status',)

    
class ConsultationsForm(forms.ModelForm):

    class Meta():

        model = Consultations
        fields = ('doctor', 'block', 'user', 'appointment', 'symtoms', 'treatment', 'medicaments', 'price', 'payment')

clinica_dental/appointments/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.models import User

from users.models import Profile
from appointments.models import WorkBlocks, Appointments
from appointments.forms import WorkBlockForm, AppointmentsForm, EditAppointmentsForm, ConsultationsForm
from .models import WorkBlocks
from medical_records.models import MedicalRecords


# --- APPOINTMENTS --- #


class AppointmentsHomeView(LoginRequiredMixin, ListView):

    template_name = 'appointments/home.html'
    model = Profile
    context_object_name = 'usuarios'


class AppointmentsFeedView(LoginRequiredMixin, ListView):

    template_name = 'appointments/feed.html'
    model = Appointments
    context_object_name = 'appointments'

    
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['blocks'] = WorkBlocks.objects.all()
        context['records'] = MedicalRecords.objects.filter(user_id=self.request.user.id)

        if not context['records']:
            context['record'] = True # No existe el medical record de este paciente

        return context


class AppointmentsFeedDoctorView(LoginRequiredMixin, ListView):

    template_name = 'appointments/feed_doctor.html'
    model = Appointments
    context_object_name = 'appointments'


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['blocks'] = WorkBlocks.objects.filter(doctor_id=self.request.user.id)
        context['users'] = User.objects.all()

        return context


class AddAppointmentsPreview(LoginRequiredMixin, ListView):

    template_name = 'appointments/add_preview.html'
    model = WorkBlocks
    context_object_name = 'blocks'


class AddAppointmentsView(LoginRequiredMixin, CreateView):

    template_name = 'appointments/add.html'
    form_class = AppointmentsForm
    success_url = reverse_lazy('appointments:feed')


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['user_id'] = self.request.user.id
        context['appointments'] = Appointments.objects.filter(block_id = self.kwargs['block_id'])
        
        if not context['appointments']:
            context['appointment'] = True  # Esta vacío 

        context['block_id'] = self.kwargs['block_id']

        return context

    
class DeleteAppointmentsView(LoginRequiredMixin, DeleteView):

    model = Appointments
    template_name = 'appointments/delete.html'
    success_url = reverse_lazy('appointments:feed')


class UpdateAppointmentsView(LoginRequiredMixin, UpdateView):

    template_name = 'appointments/update.html'
    model = Appointments
    form_class = EditAppointmentsForm
    success_url = reverse_lazy('appointments:feed_doctors')


# --- WORK BLOCKS --- #


class WorkBlocksView(LoginRequiredMixin, ListView):

    template_name = 'work_blocks/feed.html'
    model = WorkBlocks
    context_object_name = 'blocks'


class AddWorkBlocksView(LoginRequiredMixin, CreateView):

    template_name = 'work_blocks/add.html'
    form_class = WorkBlockForm
    success_url = reverse_lazy('appointments:work_blocks')


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['doctor_id'] = self.request.user.id
        context['doctor_name'] = self.request.user.get_full_name

        return context

    
class DeleteWorkBlocksView(LoginRequiredMixin, DeleteView):

    model = WorkBlocks
    template_name = 'work_blocks/delete.html'
    success_url = reverse_lazy('appointments:work_blocks')


# --- CONSULTATIONS --- #


class AddConsultationsView(LoginRequiredMixin, CreateView):

    template_name = 'consultations/add.html'
    form_class = ConsultationsForm
    success_url = reverse_lazy('appointments:feed_doctors')


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['data'] = Appointments.objects.get(pk = self.kwargs['appointment_id'])
        context['doctor_id'] = self.request.user.id
        context['appointment_id'] = self.kwargs['appointment_id']

        return context

    
    def form_valid(self, form, **kwargs):

        response = super(AddConsultationsView, self).form_valid(form)
        query = Appointments.objects.filter(pk = self.kwargs['appointment_id'])
        query.update(status='Done')

        return response

clinica_dental/templates/appointments/add.html
{% extends "base.html" %}

{% block head_content %}

<title> Clínica Dental Adolf Dental Care Add Appointment </title>

{% endblock %}

{% block container %}

    <style>
        body {
            overflow: hidden;
        }

        form {
            padding: 10%;
        }
    </style>

    {% if appointment == True %}

    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        <input type="hidden" name="user" value="{{ user_id }}">
        <input type="hidden" name="block" value="{{ block_id }}">
        <input type="hidden" name="status" value="Stand By">

        <p>Are you sure you want to add this Appointment? </p>
        <button class="btn btn-info" type="submit"> Add </button>
        <a href="{% url 'appointments:add_preview' %}" class="btn btn-primary"> Cancel </a>

    </form>

    {% else %}
    
    <form>
        <p> This appointment is already taken, please go back and select another one. </p>
        <a href="{% url 'appointments:add_preview' %}" class="btn btn-primary"> Go Back </a>
    </form>
    
    {% endif %}

{% endblock %}

clinica_dental/templates/appointments/add_preview.html
{% extends "base.html" %}

{% block head_content %}
<title> Clínica Dental Adolf Dental Care Available Appointments </title>
{% endblock %}

{% block container %}

<style>
    table,
    form {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin: 100px 0 0 25px;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        text-align: center;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    body {
        overflow: hidden;
    }

    .container-2{
        margin: 50px 0 0px 25px;
        padding-left: 43%;
    }
</style>

<div class="container">
    <div class="row">

        <table>

            <tr>
                <th> Doctor ID </th>
                <th> Doctor </th>
                <th> Hour </th>
                <th> Day </th>
                <th> Status </th>
            </tr>

            {% for block in blocks %}
            <tr>
                <td>
                    {{ block.doctor_id }}
                </td>
                <td>
                    {{ block.doctor_name}}
                </td>
                <td>
                    {% if block.hour == '1' %}
                        7:00 - 8:30
                    {% elif block.hour == '2' %}
                        8:45 - 10:15
                    {% elif block.hour == '3' %}
                        10:30 - 12:00
                    {% elif block.hour == '4' %}
                        12:15 - 1:45
                    {% elif block.hour == '5' %}
                        2:00 - 3:30
                    {% elif block.hour == '6' %}
                        3:45 - 5:15
                    {% elif block.hour == '7' %}
                        5:30 - 7:00
                    {% endif %}
                </td>
                <td>
                    {% if block.day == '1' %}
                        Monday
                    {% elif block.day == '2' %}
                        Tuesday
                    {% elif block.day == '3' %}
                        Wednesday
                    {% elif block.day == '4' %}
                        Thrusday
                    {% elif block.day == '5' %}
                        Friday         
                    {% endif %}      
                </td>
                <td>
                    <a href="{% url 'appointments:add_appointments' block.id %}" class="btn btn-info"> Select </a>
                </td>
            </tr>
            {% endfor %}

        </table>

    </div>
</div>

{% endblock %}

clinica_dental/templates/appointments/feed.html
{% extends "base.html" %}

{% block head_content %}
<title> Clínica Dental Adolf Dental Care Appointments Feed </title>
{% endblock %}

{% block container %}

<style>
    table,
    form {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin: 100px 0 0 25px;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        text-align: center;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    body {
        overflow: hidden;
    }

    .container-2 {
        margin: 50px 0 0px 25px;
        padding-left: 43%;
    }
</style>

<div class="container">
    <div class="row">

        {% if record == True %}
        <form>
            <p> You must complete your data to be able to make an appointment. </p>
            <a href="{% url 'medical_records:create' %}" class="btn btn-info"> Complete Data </a>
        </form>
        {% else %}
            <table>
                <tr>
                    <th> Day </th>
                    <th> Hour </th>
                    <th> Doctor </th>
                    <th> Status </th>
                    <th> Options </th>
                </tr>
                    {% for appointment in appointments %}
                        {% if user.id == appointment.user_id %}
                        <tr>
                            {% for block in blocks %}
                            {% if appointment.block_id == block.id %}
                            <td>
                                {% if block.day == '1' %}
                                Monday
                                {% elif block.day == '2' %}
                                    Tuesday
                                {% elif block.day == '3' %}
                                    Wednesday
                                {% elif block.day == '4' %}
                                    Thrusday
                                {% elif block.day == '5' %}
                                    Friday         
                                {% endif %}
                            </td>
                            <td>
                                {% if block.hour == '1' %}
                                7:00 - 8:30
                                {% elif block.hour == '2' %}
                                    8:45 - 10:15
                                {% elif block.hour == '3' %}
                                    10:30 - 12:00
                                {% elif block.hour == '4' %}
                                    12:15 - 1:45
                                {% elif block.hour == '5' %}
                                    2:00 - 3:30
                                {% elif block.hour == '6' %}
                                    3:45 - 5:15
                                {% elif block.hour == '7' %}
                                    5:30 - 7:00
                                {% endif %}
                            </td>
                            <td>
                                {{ block.doctor_name }}
                            </td>
                            {% endif %}
                            {% endfor %}
                            <td>
                                {{ appointment.status }}
                            </td>
                            {% if appointment.status == 'Stand By' %}
                            <td>
                                <a href="{% url 'appointments:delete_appointments' appointment.id %}" class="btn btn-danger"> Cancel </a>
                            </td>
                            {% endif %}
                        </tr>
                        {% endif %}
                    {% endfor %}    
            </table>

            <div class="container-2">
                <a href="{% url 'appointments:add_preview' %}" class="btn btn-info"> Add Appointment </a>
            </div>
        {% endif %}
    </div>
</div>

{% endblock %}

clinica_dental/templates/appointments/feed_doctor.html
{% extends "base.html" %}

{% block head_content %}
<title> Clínica Dental Adolf Dental Care Appointments Feed </title>
{% endblock %}

{% block container %}

<style>
    table,
    form {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin: 100px 0 0 25px;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        text-align: center;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    body {
        overflow: hidden;
    }

    .container-2 {
        margin: 50px 0 0px 25px;
        padding-left: 43%;
    }
</style>

<div class="container">
    <div class="row">

        <table>
            <tr>
                <th> Day </th>
                <th> Hour </th>
                <th> Pacient </th>
                <th> Status </th>
                <th> Options </th>
                <th> Appointment </th>
                <th> Bill </th>
            </tr>
            {% for appointment in appointments %}
                <tr>
                    {% for block in blocks %}
                        {% if appointment.block_id == block.id %}
                        <td>
                            {% if block.day == '1' %}
                            Monday
                            {% elif block.day == '2' %}
                            Tuesday
                            {% elif block.day == '3' %}
                            Wednesday
                            {% elif block.day == '4' %}
                            Thrusday
                            {% elif block.day == '5' %}
                            Friday
                            {% endif %}
                        </td>
                        <td>
                            {% if block.hour == '1' %}
                            7:00 - 8:30
                            {% elif block.hour == '2' %}
                            8:45 - 10:15
                            {% elif block.hour == '3' %}
                            10:30 - 12:00
                            {% elif block.hour == '4' %}
                            12:15 - 1:45
                            {% elif block.hour == '5' %}
                            2:00 - 3:30
                            {% elif block.hour == '6' %}
                            3:45 - 5:15
                            {% elif block.hour == '7' %}
                            5:30 - 7:00
                            {% endif %}
                        </td>

                        {% for user in users %}
                            {% if user.id == appointment.user_id %}
                            <td>
                                {{ user.get_full_name }}
                            </td>
                            {% endif %}
                        {% endfor %}

                        <td>
                            {{ appointment.status }}
                        </td>
    
                        {% if appointment.status == 'Stand By' %}
                        <td>
                            <a href="{% url 'appointments:update_appointments' appointment.id %}" class="btn btn-danger"> Cancel </a>
                        </td>
    
                        <td>
                            <a href="{% url 'appointments:add_consultations' appointment.id %}" class="btn btn-info"> Manage </a>
                        </td>
                        {% else %}
                        <td>
                            ---
                        </td>
                        <td>
                            ---
                        </td>
                        {% endif %}

                        {% if appointment.status == 'Done' %}
                        <td>
                            <a href="{% url 'medical_records:send_bill' appointment.id %}" class="btn btn-info"> Send </a>
                        </td>
                        {% else %}
                        <td>
                            ---
                        </td>
                        {% endif %}

                        {% endif %}

                    {% endfor %}
                </tr>
            {% endfor %}
        </table>
    </div>
</div>

{% endblock %}

clinica_dental/templates/appointments/home.html
{% extends "base.html" %}

{% block head_content %}
<title> Clínica Dental Adolf Dental Care </title>
{% endblock %}

{% block container %}

<style>
    .row, .container-h1 {
        margin-top: 100px;
        align-content: center;
    }

    h1{
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        text-align: center;
    }

    body {
        overflow: hidden;
    }

</style>

<body>

    <div class="container-h1">
        <div class="row">

            <div class="container">
                <h1> Welcome to Clínica Dental Adolf Care </h1>
            </div>

            {% for usuario in usuarios %}
                {% if usuario.user_id == user.id and usuario.role == 'Super User' and usuario.bloqued != True %}
                
                <div class="row justify-content-md-center">
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"> Manage Users </h5>
                                <p class="card-text"> Manage the users that are registered in the system.
                                </p>
                                <a href="{% url 'users:superuser' %}" class="btn btn-primary">Go somewhere</a>
                            </div>
                        </div>
                    </div>
    
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"> General Statistics </h5>
                                <p class="card-text">View and manage the general statistics of the clinic.
                                </p>
                                <a href="{% url 'users:statistics' %}" class="btn btn-primary">Go somewhere</a>
                            </div>
                        </div>
                    </div>
    
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"> Manage Payments </h5>
                                <p class="card-text">Manage the percentage of payments of each doctor.
                                </p>
                                <a href="" class="btn btn-primary">Go somewhere</a>
                            </div>
                        </div>
                    </div>
    
                </div>
                
                {% endif %}
            {% endfor %}

            {% for usuario in usuarios %}
                {% if usuario.user_id == user.id and usuario.role == 'Pacient' and usuario.bloqued != True %}
                
                <div class="row justify-content-md-center">
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"> Add Appointments </h5>
                                <p class="card-text">Add and manage your appointments with the doctors. 
                                </p>
                                <a href="{% url 'appointments:feed' %}" class="btn btn-primary">Go somewhere</a>
                            </div>
                        </div>
                    </div>
    
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"> Manage Medical Record </h5>
                                <p class="card-text"> View and manage your medical records saved in the clinic.
                                </p>
                                <a href="{% url 'medical_records:feed' %}" class="btn btn-primary">Go somewhere</a>
                            </div>
                        </div>
                    </div>
    
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"> Account Status </h5>
                                <p class="card-text"> Check your account status and make payments. 
                                </p>
                                <a href="{% url 'medical_records:account' %}" class="btn btn-primary">Go somewhere</a>
                            </div>
                        </div>
                    </div>
    
                </div>
                
                {% endif %}
            {% endfor %}

            {% for usuario in usuarios %}
                {% if usuario.user_id == user.id and usuario.role == 'Doctor' and usuario.bloqued != True %}
                
                <div class="row justify-content-md-center">
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"> Manage Appointments </h5>
                                <p class="card-text"> Confirm, modify or cancel the appointments that you have. 
                                </p>
                                <a href="{% url 'appointments:feed_doctors' %}" class="btn btn-primary">Go somewhere</a>
                            </div>
                        </div>
                    </div>
    
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"> Manage Work Blocks </h5>
                                <p class="card-text"> Manage the days and hours of work as your convinience. 
                                </p>
                                <a href="{% url 'appointments:work_blocks' %}" class="btn btn-primary">Go somewhere</a>
                            </div>
                        </div>
                    </div>
    
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"> Manage Medical Records </h5>
                                <p class="card-text"> Manage the medical records of your pacients. 
                                </p>
                                <a href="{% url 'medical_records:feed_doctors' %}" class="btn btn-primary">Go somewhere</a>
                            </div>
                        </div>
                    </div>
    
                </div>
                
                {% endif %}

                {% if usuario.bloqued == True %}
                
                <div class="row justify-content-md-center">
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"> Contact Us </h5>
                                <p class="card-text"> Send an email to CDAC@hotmail.com for more information. 
                                </p>
                            </div>
                        </div>
                    </div>
    
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"> ¡User Bloqued! </h5>
                                <p class="card-text"> Please contact us for more information about your profile. 
                                </p>
                            </div>
                        </div>
                    </div>
    
                    <div class="col-sm-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title"> Call Us </h5>
                                <p class="card-text"> Call us to +58 7000 0000 for more information. 
                                </p>
                            </div>
                        </div>
                    </div>
    
                </div>

                {% endif %}

            {% endfor %}

        </div>
    </div>
</body>

{% endblock %}