clinica_dental/appointments/urls.py
from django.urls import path
from appointments import views


urlpatterns = [

    path(
        route = '',
        view = views.AppointmentsHomeView.as_view(),
        name = "home",
    ),

    path(
        route = 'appointments/work_blocks',
        view = views.WorkBlocksView.as_view(),
        name = "work_blocks",
    ),

    path(
        route = 'appointments/add_work_blocks',
        view = views.AddWorkBlocksView.as_view(),
        name = "add_work_blocks",
    ),

    path(
        route = 'appointments/delete_work_blocks/<int:pk>',
        view = views.DeleteWorkBlocksView.as_view(),
        name = "delete_work_blocks",
    ),

    path(
        route = 'appointments/feed',
        view = views.AppointmentsFeedView.as_view(),
        name = "feed",
    ),

    path(
        route = 'appointments/add_preview',
        view = views.AddAppointmentsPreview.as_view(),
        name = "add_preview",
    ),

    path(
        route = 'appointments/add_appointment/<int:block_id>',
        view = views.AddAppointmentsView.as_view(),
        name = "add_appointments",
    ),

    path(
        route = 'appointments/delete_appointment/<int:pk>',
        view = views.DeleteAppointmentsView.as_view(),
        name = "delete_appointments",
    ),

    path(
        route = 'appointments/feed_doctors',
        view = views.AppointmentsFeedDoctorView.as_view(),
        name = "feed_doctors",
    ),

    path(
        route = 'appointments/update_appointment/<int:pk>',
        view = views.UpdateAppointmentsView.as_view(),
        name = "update_appointments",
    ),

    path(
        route = 'consultations/add/<int:appointment_id>',
        view = views.AddConsultationsView.as_view(),
        name = "add_consultations",
    ),

]

clinica_dental/clinica_dental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('appointments.urls', 'appointments'), namespace='appointments')),

    path('users/', include(('users.urls', 'users'), namespace='users')),
    
    path('medical_records/', include(('medical_records.urls', 'medical_records'), namespace='medical_records')),

    path('consultations/', include(('consultations.urls', 'consultations'), namespace='consultations')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinica_dental/users/urls.py
from django.urls import path
from users import views


urlpatterns = [

    path(
        route = 'login/',
        view = views.LoginView.as_view(),
        name = "login",
    ),

    path(
        route = 'signup/',
        view = views.SignUpView.as_view(),
        name = "signup",
    ),

    path(
        route = 'logout/',
        view = views.LogOutView.as_view(),
        name = "logout",
    ),

    path(
        route = 'superuser/',
        view = views.SuperUserView.as_view(),
        name = "superuser",
    ),

    path(
        route = 'edit_user/<int:pk>',
        view = views.EditUserView.as_view(),
        name = "edit_user",
    ),

    path(
        route = 'statistics',
        view = views.StatisticsFeedView.as_view(),
        name = "statistics",
    ),

]

clinica_dental/templates/work_blocks/add.html
{% extends "base.html" %}

{% block head_content %}

    <title> Clínica Dental Adolf Dental Care Add Work Blocks </title>

{% endblock %}

{% block container %}

<style>

    body{
        overflow: hidden;
    }

    form {
        padding: 10%;
    }

</style>


    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}
        
        <input type="hidden" name="doctor" value="{{ doctor_id }}">
        <input type="hidden" name="doctor_name" value="{{ doctor_name }}">

        <div class="form-group">
            <label> Select Hour: </label>
            <select class="form-control" name="hour">
                <option value="1"> 7:00 - 8:30 </option>
                <option value="2"> 8:45 - 10:15 </option>
                <option value="3"> 10:30 - 12:00 </option>
                <option value="4"> 12:15 - 1:45 </option>
                <option value="5"> 2:00 - 3:30 </option>
                <option value="6"> 3:45 - 5:15 </option>
                <option value="7"> 5:30 - 7:00 </option>
            </select>
        </div>

        <div class="form-group">
            <label> Select Day: </label>
            <select class="form-control" name="day">
                <option value="1"> Monday </option>
                <option value="2"> Tuesday </option>
                <option value="3"> Wednesday </option>
                <option value="4"> Thrusday </option>
                <option value="5"> Friday </option>
            </select>
        </div>

        <button class="btn btn-info" type="submit"> Add </button>
        <a href="{% url 'appointments:work_blocks' %}" class="btn btn-primary"> Cancel </a>

    </form>

{% endblock %}

clinica_dental/templates/work_blocks/delete.html
{% extends "base.html" %}

{% block head_content %}

    <title> Clínica Dental Adolf Dental Care Delete Work Blocks </title>

{% endblock %}

{% block container %}

<style>

    body{
        overflow: hidden;
    }

    form {
        padding: 10%;
    }

</style>


    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        <p>Are you sure you want to delete this Work Block? </p>

        <button class="btn btn-danger" type="submit"> Delete </button>
        <a href="{% url 'appointments:work_blocks' %}" class="btn btn-primary"> Cancel </a>

    </form>

{% endblock %}

clinica_dental/templates/work_blocks/feed.html
{% extends "base.html" %}

{% block head_content %}
<title> Clínica Dental Adolf Dental Care Work Blocks </title>
{% endblock %}

{% block container %}

<style>
    table,
    form {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin: 100px 0 0 25px;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        text-align: center;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    body {
        overflow: hidden;
    }

    .container-2{
        margin: 50px 0 0px 25px;
        padding-left: 43%;
    }
</style>

<div class="container">
    <div class="row">

        <table>

            <tr>
                <th> Doctor ID </th>
                <th> Doctor </th>
                <th> Hour </th>
                <th> Day </th>
                <th> Status </th>
            </tr>

            {% for block in blocks %}
            <tr>
                <td>
                    {{ block.doctor_id }}
                </td>
                <td>
                    {{ block.doctor_name}}
                </td>
                <td>
                    {% if block.hour == '1' %}
                        7:00 - 8:30
                    {% elif block.hour == '2' %}
                        8:45 - 10:15
                    {% elif block.hour == '3' %}
                        10:30 - 12:00
                    {% elif block.hour == '4' %}
                        12:15 - 1:45
                    {% elif block.hour == '5' %}
                        2:00 - 3:30
                    {% elif block.hour == '6' %}
                        3:45 - 5:15
                    {% elif block.hour == '7' %}
                        5:30 - 7:00
                    {% endif %}
                </td>
                <td>
                    {% if block.day == '1' %}
                        Monday
                    {% elif block.day == '2' %}
                        Tuesday
                    {% elif block.day == '3' %}
                        Wednesday
                    {% elif block.day == '4' %}
                        Thrusday
                    {% elif block.day == '5' %}
                        Friday         
                    {% endif %}      
                </td>
                <td>
                    {% if user.id == block.doctor_id %}
                        <a href="{% url 'appointments:delete_work_blocks' block.id %}" class="btn btn-danger"> Delete </a>
                    {% else %}
                        ---
                    {% endif %}
                </td>
            </tr>
            {% endfor %}

        </table>

        <div class="container-2">
            <a href="{% url 'appointments:add_work_blocks' %}" class="btn btn-info"> Add Work Block </a>
        </div>

    </div>
</div>

{% endblock %}