clinica_dental/clinica_dental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [

    path('admin/', admin.site.urls),

    path('', include(('appointments.urls', 'appointments'), namespace='appointments')),

    path('users/', include(('users.urls', 'users'), namespace='users')),
    
    path('medical_records/', include(('medical_records.urls', 'medical_records'), namespace='medical_records')),

    path('consultations/', include(('consultations.urls', 'consultations'), namespace='consultations')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

clinica_dental/medical_records/urls.py
from django.urls import path
from medical_records import views


urlpatterns = [

    path(
        route = 'medical_records/feed',
        view = views.MedicalRecordsFeedView.as_view(),
        name = 'feed',
    ),

    path(
        route = 'medical_records/create',
        view = views.CreateMedicalRecordView.as_view(),
        name = 'create',
    ),

    path(
        route = 'medical_records/feed_doctors',
        view = views.MedicalRecordsDoctorsFeedView.as_view(),
        name = 'feed_doctors',
    ),

    path(
        route = 'medical_records/consultations_feed/<int:user_id>',
        view = views.ConsultationsDoctorFeedView.as_view(),
        name = 'feed_consultations',
    ),

    path(
        route = 'medical_records/consultations_feed_pacient/<int:user_id>',
        view = views.ConsultationsPacientFeedView.as_view(),
        name = 'feed_pacient',
    ),

    path(
        route = 'medical_records/account',
        view = views.AccountFeedView.as_view(),
        name = 'account',
    ),

    path(
        route = 'medical_records/send_bill/<int:appointment_id>',
        view = views.SendBillView.as_view(),
        name = 'send_bill',
    ),

]

clinica_dental/users/urls.py
from django.urls import path
from users import views


urlpatterns = [

    path(
        route = 'login/',
        view = views.LoginView.as_view(),
        name = "login",
    ),

    path(
        route = 'signup/',
        view = views.SignUpView.as_view(),
        name = "signup",
    ),

    path(
        route = 'logout/',
        view = views.LogOutView.as_view(),
        name = "logout",
    ),

    path(
        route = 'superuser/',
        view = views.SuperUserView.as_view(),
        name = "superuser",
    ),

    path(
        route = 'edit_user/<int:pk>',
        view = views.EditUserView.as_view(),
        name = "edit_user",
    ),

    path(
        route = 'statistics',
        view = views.StatisticsFeedView.as_view(),
        name = "statistics",
    ),

]

clinica_dental/medical_records/models.py
from django.db import models
from django.contrib.auth.models import User

from users.models import Profile
from appointments.models import Consultations


class MedicalRecords(models.Model):

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    
    dni = models.CharField(max_length=10)
    age = models.CharField(max_length=3)
    birthday = models.DateField()
    marital_status = models.CharField(max_length=255)
    nacionality = models.CharField(max_length=255)
    address = models.CharField(max_length=255)

    user = models.OneToOneField(User, on_delete=models.CASCADE)


class AccountStatus(models.Model):

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    status = models.CharField(max_length=10, default='Pending')

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    consultation = models.ForeignKey(Consultations, on_delete=models.CASCADE)

clinica_dental/medical_records/forms.py
from django import forms

from medical_records.models import MedicalRecords, AccountStatus


class MedicalRecordForm(forms.ModelForm):

    class Meta():

        model = MedicalRecords
        fields = ('dni', 'age', 'birthday', 'marital_status', 'nacionality', 'address', 'user')


class AccountStatusForm(forms.ModelForm):

    class Meta():

        model = AccountStatus
        fields = ('status', 'user', 'consultation')

clinica_dental/medical_records/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.contrib.auth.models import User

from users.models import Profile
from appointments.models import WorkBlocks, Appointments, Consultations
from appointments.forms import WorkBlockForm, AppointmentsForm
from medical_records.models import MedicalRecords, AccountStatus
from medical_records.forms import MedicalRecordForm, AccountStatusForm


# --- MEDICAL RECORDS --- #


class MedicalRecordsFeedView(LoginRequiredMixin, ListView):

    template_name = 'medical_records/feed.html'
    model = MedicalRecords
    context_object_name = 'records'


class CreateMedicalRecordView(LoginRequiredMixin, CreateView):

    template_name = 'medical_records/update.html'
    form_class = MedicalRecordForm
    success_url = reverse_lazy('appointments:feed')

    
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['user_id'] = self.request.user.id

        return context


class MedicalRecordsDoctorsFeedView(LoginRequiredMixin, ListView):

    template_name = 'medical_records/feed_doctors.html'
    model = MedicalRecords
    context_object_name = 'records'


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['consultations'] = Consultations.objects.filter(doctor_id = self.request.user.id)
        context['users'] = User.objects.all()

        return context


# --- CONSULTATIONS --- #


class ConsultationsDoctorFeedView(LoginRequiredMixin, ListView):

    template_name = 'medical_records/consultations_feed.html'
    model = Consultations
    context_object_name = 'consultations'


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['user_id'] = self.kwargs['user_id']
        context['doctor_id'] = self.request.user.id
        context['blocks'] = WorkBlocks.objects.all()
        context['bills'] = AccountStatus.objects.all()

        return context


class ConsultationsPacientFeedView(LoginRequiredMixin, ListView):

    template_name = 'medical_records/consultations_feed_pacient.html'
    model = Consultations
    context_object_name = 'consultations'


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['user_id'] = self.kwargs['user_id']
        context['blocks'] = WorkBlocks.objects.all()
        context['users'] = User.objects.all()

        return context


# --- ACCOUNT STATUS --- #


class AccountFeedView(LoginRequiredMixin, ListView):

    template_name = 'users/account.html'
    model = AccountStatus
    context_object_name = 'accounts'

    
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['user_id'] = self.request.user.id
        context['users'] = User.objects.all()
        context['blocks'] = WorkBlocks.objects.all()
        context['consultations'] = Consultations.objects.all()

        return context


class SendBillView(LoginRequiredMixin, CreateView):

    template_name = 'medical_records/send_bill.html'
    form_class = AccountStatusForm
    success_url = reverse_lazy('appointments:feed_doctors')

    
    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['consultation'] = Consultations.objects.get(appointment_id = self.kwargs['appointment_id'])
        consultation = Consultations.objects.get(appointment_id = self.kwargs['appointment_id'])
        bills = AccountStatus.objects.all()

        for bill in bills:
            
            if bill.consultation_id == consultation.pk:

                context['record'] = False

        return context

clinica_dental/templates/medical_records/consultations_feed.html
{% extends "base.html" %}

{% block head_content %}
<title> Clínica Dental Adolf Dental Care Medical Records Consultations </title>
{% endblock %}

{% block container %}

<style>
    table,
    form {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin: 100px 0 0 25px;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 10px;
        text-align: center;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    body {
        overflow: hidden;
    }

    .container-2 {
        margin: 50px 0 0px 25px;
        padding-left: 43%;
    }
</style>

<div class="container">
    <div class="row">

        <table>

            <tr>
                <th> Day </th>
                <th> Hour </th>
                <th> Symtoms </th>
                <th> Treatment </th>
                <th> Medicaments </th>
                <th> Price </th>
                <th> Payment </th>
                <th> Status </th>
            </tr>

            {% for consultation in consultations %}
            {% if consultation.doctor_id == doctor_id and consultation.user_id == user_id %}
            <tr>
                {% for block in blocks %}
                {% if block.pk == consultation.block_id %}
                <td>
                    {% if block.hour == '1' %}
                        7:00 - 8:30
                    {% elif block.hour == '2' %}
                        8:45 - 10:15
                    {% elif block.hour == '3' %}
                        10:30 - 12:00
                    {% elif block.hour == '4' %}
                        12:15 - 1:45
                    {% elif block.hour == '5' %}
                        2:00 - 3:30
                    {% elif block.hour == '6' %}
                        3:45 - 5:15
                    {% elif block.hour == '7' %}
                        5:30 - 7:00
                    {% endif %}
                </td>
                <td>
                    {% if block.day == '1' %}
                        Monday
                    {% elif block.day == '2' %}
                        Tuesday
                    {% elif block.day == '3' %}
                        Wednesday
                    {% elif block.day == '4' %}
                        Thrusday
                    {% elif block.day == '5' %}
                        Friday         
                    {% endif %}      
                </td>
                {% endif %}
                {% endfor %}
                
                <td>
                    {{ consultation.symtoms }}
                </td>
                <td>
                    {{ consultation.treatment }}
                </td>
                <td>
                    {{ consultation.medicaments }}
                </td>
                <td>
                    {{ consultation.price }}$
                </td>
                <td>
                    {{ consultation.payment }}
                </td>
                
                {% for bill in bills %}
                {% if bill.consultation_id == consultation.pk %}
                <td>
                    {{ bill.status }}
                </td>
                {% endif %}
                {% endfor %}
                
            </tr>
            {% endif %}
            {% endfor %}

        </table>

        <div class="container-2">
            <a href="{% url 'medical_records:feed_doctors' %}" class="btn btn-info"> Go back </a>
        </div>

    </div>
</div>

{% endblock %}

clinica_dental/templates/medical_records/consultations_feed_pacient.html
{% extends "base.html" %}

{% block head_content %}
<title> Clínica Dental Adolf Dental Care Consultations Feed Pacient </title>
{% endblock %}

{% block container %}

<style>
    table,
    form {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin: 100px 0 0 25px;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        text-align: center;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    body {
        overflow: hidden;
    }

    .container-2 {
        margin: 50px 0 0px 25px;
        padding-left: 43%;
    }
</style>

<div class="container">
    <div class="row">

        <table>

            <tr>
                <th> Day </th>
                <th> Hour </th>
                <th> Doctor Name </th>
                <th> Symtoms </th>
                <th> Treatment </th>
                <th> Medicaments </th>
                <th> Price </th>
                <th> Payment </th>
            </tr>

            {% for consultation in consultations %}
            {% if consultation.user_id == user_id %}
            <tr>
                {% for block in blocks %}
                {% if block.pk == consultation.block_id %}
                <td>
                    {% if block.hour == '1' %}
                        7:00 - 8:30
                    {% elif block.hour == '2' %}
                        8:45 - 10:15
                    {% elif block.hour == '3' %}
                        10:30 - 12:00
                    {% elif block.hour == '4' %}
                        12:15 - 1:45
                    {% elif block.hour == '5' %}
                        2:00 - 3:30
                    {% elif block.hour == '6' %}
                        3:45 - 5:15
                    {% elif block.hour == '7' %}
                        5:30 - 7:00
                    {% endif %}
                </td>
                <td>
                    {% if block.day == '1' %}
                        Monday
                    {% elif block.day == '2' %}
                        Tuesday
                    {% elif block.day == '3' %}
                        Wednesday
                    {% elif block.day == '4' %}
                        Thrusday
                    {% elif block.day == '5' %}
                        Friday         
                    {% endif %}      
                </td>
                {% endif %}
                {% endfor %}
                
                {% for user in users %}
                {% if user.id == consultation.doctor_id %}
                <td>
                    {{ user.get_full_name }}
                </td>
                {% endif %}
                {% endfor %}
                
                <td>
                    {{ consultation.symtoms }}
                </td>
                <td>
                    {{ consultation.treatment }}
                </td>
                <td>
                    {{ consultation.medicaments }}
                </td>
                <td>
                    {{ consultation.price }}$
                </td>
                <td>
                    {{ consultation.payment }}
                </td>
            </tr>
            {% endif %}
            {% endfor %}

        </table>

        <div class="container-2">
            <a href="{% url 'medical_records:feed' %}" class="btn btn-info"> Go back </a>
        </div>

    </div>
</div>

{% endblock %}

clinica_dental/templates/medical_records/feed.html
{% extends "base.html" %}

{% block head_content %}
<title> Clínica Dental Adolf Dental Care Medical Records Feed </title>
{% endblock %}

{% block container %}

<style>
    table,
    form {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin: 100px 0 0 25px;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        text-align: center;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    body {
        overflow: hidden;
    }

    .container-2 {
        margin: 50px 0 0px 25px;
        padding-left: 43%;
    }
</style>

<div class="container">
    <div class="row">

        <table>

            <tr>
                <th> DNI </th>
                <th> Age </th>
                <th> Birthday </th>
                <th> Marital Status </th>
                <th> Nacionality </th>
                <th> Address </th>
                <th> Consultations </th>
            </tr>

            {% for record in records %}
            {% if user.id == record.user_id %}
            <tr>
            
                <td>
                    {{ record.dni }}
                </td>
                <td>
                    {{ record.age }}
                </td>
                <td>
                    {{ record.birthday }}
                </td>
                <td>
                    {{ record.marital_status }}
                </td>
                <td>
                    {{ record.nacionality }}
                </td>
                <td>
                    {{ record.address }}
                </td>
                <td>
                    <a href="{% url 'medical_records:feed_pacient' record.user_id %}" class="btn btn-info"> Check </a>
                </td>
            </tr>
            {% endif %}
            {% endfor %}

        </table>

    </div>
</div>

{% endblock %}

clinica_dental/templates/medical_records/feed_doctors.html
{% extends "base.html" %}

{% block head_content %}
<title> Clínica Dental Adolf Dental Care Medical Records Feed Doctors </title>
{% endblock %}

{% block container %}

<style>
    table,
    form {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 100%;
        margin: 100px 0 0 25px;
    }

    td,
    th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
        text-align: center;
    }

    tr:nth-child(even) {
        background-color: #dddddd;
    }

    body {
        overflow: hidden;
    }

    .container-2 {
        margin: 50px 0 0px 25px;
        padding-left: 43%;
    }
</style>

<div class="container">
    <div class="row">

        <table>

            <tr>
                <th> Pacient </th>
                <th> DNI </th>
                <th> Age </th>
                <th> Birthday </th>
                <th> Marital Status </th>
                <th> Nacionality </th>
                <th> Address </th>
                <th> Consultations </th>
            </tr>

            {% for record in records %}
                {% for consultation in consultations %}
                    {% if record.user_id == consultation.user_id %}
                    <tr>
                        {% for user in users %}
                        {% if user.pk == record.user_id %}
                        <td>
                            {{ user.get_full_name }}
                        </td>
                        {% endif %}
                        {% endfor %}
                        <td>
                            {{ record.dni }}
                        </td>
                        <td>
                            {{ record.age }}
                        </td>
                        <td>
                            {{ record.birthday }}
                        </td>
                        <td>
                            {{ record.marital_status }}
                        </td>
                        <td>
                            {{ record.nacionality }}
                        </td>
                        <td>
                            {{ record.address }}
                        </td>
                        <td>
                            <a href="{% url 'medical_records:feed_consultations' consultation.user_id %}" class="btn btn-info"> Check </a>
                        </td>
                    </tr>
                    {% endif %}
                {% endfor %}
            {% endfor %}

        </table>

    </div>
</div>

{% endblock %}

clinica_dental/templates/medical_records/send_bill.html
{% extends "base.html" %}

{% block head_content %}

    <title> Clínica Dental Adolf Dental Care Update Send Bill </title>

{% endblock %}

{% block container %}

<style>

    body{
        overflow: hidden;
    }

    form {
        padding: 10%;
    }

</style>

    {% if record != False %}

    <form method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        <input type="hidden" name="consultation" value="{{ consultation.pk }}">
        <input type="hidden" name="user" value="{{ consultation.user_id }}">
        <input type="hidden" name="status" value="Pending">

        <p>Are you sure you want to send the bill of this appointment to your pacient? </p>

        <button class="btn btn-info" type="submit"> Send </button>
        <a href="{% url 'appointments:feed_doctors' %}" class="btn btn-primary"> Cancel </a>

    </form>

    {% else %}

    <form>
        <p> You already have send the bill of this appointment to your pacient. </p>
        <a href="{% url 'appointments:feed_doctors' %}" class="btn btn-primary"> Go Back </a>
    </form>

    {% endif %}

{% endblock %}

clinica_dental/templates/medical_records/update.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title> Clínica Dental Adolf Dental Care Medical Record Completion </title>
{% endblock %}

{% block container %}

<style>
    body{
        overflow: hidden;
    }
</style>

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4">

            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <br>
                <input type="hidden" name="user" value="{{ user_id }}">
                
                <div class="form-group">
                    <label> DNI </label>
                    <input class="form-control" type="text" name="dni" placeholder="DNI">
                </div>

                <div class="form-group">
                    <label> Age </label>
                    <input class="form-control" type="text" name="age" placeholder="Age">
                </div>

                <div class="form-group">
                    <label> Birthday </label>
                    <input class="form-control" type="date" name="birthday">
                </div>

                <div class="form-group">
                    <label> Marital Status </label>
                    <select class="form-control" name="marital_status">
                        <option value="Single"> Single </option>
                        <option value="Married"> Married </option>
                        <option value="Divorced"> Divorced </option>
                        <option value="Widowed"> Widowed </option>
                    </select>
                </div>

                <div class="form-group">
                    <label> Nacionality </label>
                    <input class="form-control" type="text" name="nacionality" placeholder="Nacionality">
                </div>

                <div class="form-group">
                    <label> Address </label>
                    <input class="form-control" type="text" name="address" placeholder="Address">
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5"> Update Information </button>
            </form>
        </div>
    </div>
</div>

{% endblock %}